In [2]:
import numpy as np

In [3]:
input = '##################################################\n#O...........##..OO..O.OO..O......#OOOO.......#.##\n#O..#....O.....#O........O.O........O.O.O.#..O..O#\n#.O.O.......O.OO..O#O.OO...O.....O#O.##..O.......#\n#O.O...O.#...O..O##.OOO.OOO#....O....O#O.O#....O.#\n#.O#.#O.O.O.....O...O..O.....O...O.O...#OO..#....#\n#....O..O...OO.#.O.O.O..O.#........OO..O..#.O...O#\n##O...O.O..OO..O.O..OOO...O#......O.....#..O....O#\n#O.O.......OOOO....O.#OO.O...O..O.#..O#O.O.O#....#\n#.O.O......O..OO...........OO.OOO.#O.OO#O........#\n#O......O.O.O...O.#OO.....O.OOO..O.....O.O.#..OO.#\n#..O.O...O.OOO.#....O.#O....O...O..OOO...O.....O.#\n#.OO..O...O.O.O.OOOO.O...OOO..OO.........##..O...#\n#..O...O....O...O.#O..O......O.........#.......#O#\n#..O.O.#O.O.OO#..#O#..OO..O......#..O.O....#...O.#\n#....OOOO.OO....OO#.O.OOO.O.O..........#O#...#.O.#\n#...O.....OO...O.#O..O..O.......#..OOO#O..#......#\n#.OO..O.O###O.......O....OOOO..O##.O.OO.#........#\n#.O.O..O#.........#.OO.OOOO..OO..#O..O.O...OO#...#\n#.O..#OO.O.O...O.O..O..OO...OO.O...#.#.O#O.#O....#\n##.O.OO.O.O...OOO..OO.OOO...........O....#.O...#O#\n#O.........O.......OOO....#OO..O...#O.OO..#..O.OO#\n#..OO.#O........O....O...O..OO......O...O..O.....#\n#..O..OOO.O...#O#.O..O.O.O......O......O.........#\n#OO.O...OOO.......O.....@.O.O.....#O..OO...OO..O.#\n#.O.O....#O#...O.O...O.O.OO.##..O.#...O...OO...O.#\n#...OO.OOO...#OO#OO....O.#.O...O.O.........O.O#..#\n#..O.O........#...#.#....#..#O.O.#.....#.OO..O.#.#\n#..O..#OOO...#.#........O.#..O.......O.....OO...O#\n#.##OO.O......OOO.#..O....O..#O.O..O....OO.......#\n#O..OO...O...O.#O.#O.....#O....#..OO.O#.#.OOO...O#\n#O..O...O..O.O...O.O..O.#...O.OO..#.OO.O.........#\n#....OO.O.....O.OO..O....O.OO.O...OO.O.#...O..O###\n#.OO..O..##OOOO.#.O#....OO.....O..OO.O.#O.OOO..O.#\n#..O....#.....O....OO.....OOO.O..OO..OOO#O..O.O..#\n##...O.O...OO...O....OOO...O....OO...OOOOO#..#...#\n#...O###....O......O...#.......#..........O#.OO.O#\n#O.......O.O.OOO..#O....O......OOO.O.O.O.O.O.....#\n#O.#O....O...#.OO.....#O...O..O...O#.O...........#\n#.........O......O....O.......OO.O......OO....#..#\n#..O...O.....O.#.#..#O...#...O..OO..O#O#..O.O..OO#\n#.O.O#...OO...O....O......OO......O..###..O..OOO.#\n#O...#...........O..O.#.#...O.O......O....O.O.#.##\n#.#O...#..O.OO.O.O....O.OO........O...OOOOO...#O.#\n#....#......#.....O..OO..O.O.#.#.#O.........#.O..#\n#O......O.................OO.#O..#..#.#..O...OOO.#\n#...OO.#....O...OO...#.....O..O...#OO....O.....O.#\n#.O.O.O....#..#OO.......O.#...O..O#O...#O..O.....#\n#...O...O...##..#.O.#..O.O..#...O.....OO.O..#.O..#\n##################################################\n\nv>>v<>^vvv<v^v^^^>^^v<><^<<v>^v<^^>>>>>>^^vv^<v^<^>><v>v^>>^^^^<^^<^^v>v<v^>vv^><<<>^<v<^>^v^vvvv<<>>^>>v^<^v^v<>>^<^><^<^^<v^<^^<^v<<>^v^<><<>v>>^<v<<v^^^vv^vvvv^^v^^^^<^>^><v<v>v<>^>>><>v>^<^<>^^>^>v<v>><v<^<^<><><^v>><vvv>>>v^^<<^>>^>^<<>vv<vv<^^>^><^<^><>v^<vv^v^^>>>^<^v>><v^v^>v><>>^<^<<<v^^^<vvv^^>^^<^<><v>^v^>v^<>>v<>^vv>><^^<v>>^<v>^<^>>>^^>^<^<><>v>>>>>^><>vvv<<v^v<<<vv^<^v><>>><><<^<>v>^v>v^^^<<<<<^^^v>^^>^^v<v<v><v^>^^vv>v>v<v><>^>>^^^vv^>^<^^<<^^<v^v>^v<<>><v^<<^v^<vv<<^>^>>><v<>^<<<<>><<v<v<>>>^^v^v^>v>>^<v<<>v^<v>^^v^<<v>^v^>vv^v>vv><v^>v>^>^v^^>>>><>^>>^v<^^^^v^<v>^><v^vv^^v<vv^v>>^>>vvvv<><v>>^<<><v><v<^v<vvv>^<v^v><>>^^^v^><<><^<<<v>><v^<<^<^><v<^^<v>^^>><^vv>v<>><v<>^^^>^^vv^^>>><>vvv>v<^^><^vv^<v>>^<^>v<vv<^>>><>v<><^>><>>^><vv<<>^>v<v<<vv<<<<><>v^vv<^v>^v<>v^<<><^><><><^><><><^<>vvv>^^>><<>vv^v>^vv^<>v><<>^<v>vv^>^v^v>v<v<>>^v^v<><^>><^^^>^^<>v>vv^<>><^<<^<^^^>>>><><<^>v<>><v><v^>>vv<<^<<^v^<<><<<^>vvv<^<<vv><<<^v>><<><^^v>v^<^>>v^^<<^<^<<>^v<>>^v<^v<<v<<v>^v<>^<^^v\n^^>vv>v<^^>v^^<^v<^vvvv><<><^^^v<><v^^<<^<^>>>>^^^v<v<><^vv<<^>>>v<v^v>>v^v^v^>v>^>^vv<>v<<>v<^^v><<>^<v<>^v<vvv><<v<vv<v^<><>^<<>>>vv>><<^v^<<>><<>>>^<<<>v><vv^^^^<^><<^vv>><v>vv>>^^>^^^vv^v>vv>^v>^>v<^v^<><^>^^^v^v<v<^>^<>vv>v>^v^^<<^^<^<^v^v<^^^><<>>><^>>^v<<^<<>^^^>>^^^v>^v^>>^^>>v<v^<v><^>v^v>vvv>>><<>^^v>>^<^^>>v<<v<>v<^>vv^v>>v><<>^^^^>^v<^>>>^<v>vvvv<v^^^<v<<><v><^v<>>>>^>v<<>v^^<>^<v<><^v^v^>vv^<><<<>v>v>>^v^<><v^<>v<vv^<><^vv><^>vv>^^v<<v>>v>>>^<<>v^v<^v><<^^<^v<v>^^vvv^v<>>^^<v^>^v>>^<<<>^><v>>^vv>^^v>^^v^^^<>v><^^^<^<<<^<^<><<>^v<>^><v><^>v^v<v><v<^v^>vv>v^>v^v^>^vv^<^<^<^<<^v><v<>^<>^v>><v^<v><^>^^v^<<v<vv^><v^<>^><v<<>^v<^vv>>^^^<<>><v><>v>>>>>v<^<<><<v^^^<>^<vvv>^^<vvv>v>v>>>>^^><<>vv>v^^<<<<<^^>^<<>><<^<>^^<v><vv<v^<><<^>^><<vvv><^>>^vv>v<>><v^>>>^<<><v<^>^^<vvv<<>>v^^>^^<v<^^^>v^<v<^v><vv<>^^><>>^v>>><v>v>v<v^>v<vv<>v<^v<v>vv<>><v<^>>^^^^^>v>^>^<>v>^><<<>^>>v<v^^><>^>v><v^>^<<v^>^v^vvvv^v<v<v>><v^>v<v^<<v^^v>>>><>>vv^v><<<><v>v>^<<><>>^>v^v>^>><v>vv^>v^vv<<<^<>^<<^v^><\n><^v>v<<<>vv^^>>^>^<<^<>v>vv<<>>v<^<^^^<v^<<<^^vv>v<>^v^v^vv<>^v<v^>v<^^v>>^v^>><<>^>^>>v>>^vv>v><<><<v^^<^v<>^>vv^vvv><>^^^v^>^<<^^^>^v^^^vv^>^>^<^<v>>v><<v^>>^>v<<^^<v>^<<>>^><v^^><v<>^^vv><>v>><<v<><^<v><><^<v<<^v>v>^<>^><<vv<v<vvvv><vvv<^>>v>v^v^vv^v^><v<vv<v^>>v><^v^v^v<>^v<vv<v^<<v<^<^^>^<v^>^v<<<<>v<^>^<v^v><v<^^v^v^<<<v<<<^>>^>^<<<^<v>^^>>^>>v<^>>>v<>^v<v><<vv<>^v<^v^v^^>vv<^>><v^v<v^^>vv^<^^^v^>><<^<v>^vv>vv<<<>>>>>>vv>>^>>^^<^^v<v<<>v>vv^><v^v<^v^>v<<>>>>vv^^>>^>>v>^v>^<><vvv>>>^>^<^^<>v^<^>^<<v<^>><v^>>v<>>v<v^<v^v^v>v>^^^v>^v><v<><v^>vv><v^>v<^<>>v>v^^v>^^<<^^^>^<><vv^<>^>v^><<<>v<<<<<>><<<^^><^>^^<<<>^<>v^<>^<^v^>>v><>v<vv>v><v^>v^v^>v>^<>v^<>v<<>^v<^^vvvv^v^<><<^^>^^^<<v^<v><<^>v>>>v^<>>^v<<^><^v>^>^v^<<v^<>vv<>^<^vv>vvv^^<v^^<^<<^>v^vv>^^>>v^>v^<v><v<^<^<^v<^>>v^^<^^><<<v<^<^vv<v<v>>^^>>^^^<>>>>^v<v<^^^^<v<^<<vv<>v^^>>v>v<>>>^v>v<^>><<>^>><>v^^<vv<<^>v>>v<>^<^^>>>>>vvv>v>>^v><<>vv^^>><<<^<<v><<><<v^<^^<>^^>v^>^><<vvvv^v^>^>><<>>v<>v^><<v^^<^^v<^>v<^vv<<<^>>^><>vv^v^^v>^^\nvvv<>>v>v^^>v^><vvvv><<vvv^v<v^^^vvv>^v<^^<v<<vv^>>v>><^>vv>>v<>^v>^<v<>>>>^<<<v<>>^v><v>>>vv^>^^<>v<>>><v^<<vvv>^^^vv>^<^^^v<^<v>>>vv<<^vvvv^><vv>>v>v>^<vv^>^>>>>v<^^^>vv<>vv^>v<>^^>>^<<vv^>^>^<>^vv<<^^<>><>><v^v<^>>v^>^vv^vv>><<>>^v^^^<^^<>v^<^v^<^^<<><v><>^^<<<>^v^^>>^v^<>v<<vvvv^<><<<v>v>>v<^v<><>><<>>>>vv>vv<>^<<^<<v^^<>^v<v^^><v<>>vvv>^v>>^v^>^>^<v><v><>^<<^<<>vv<>v^><>v^>^>>v<^v^>^v^><v^^v^^>v^v<v<vvvv><v<<>v>^v^<<^<<v<v><v<<^^>^^v<v^^^v^<v<^v<^v^>><<v^^>^vv<v><v><>>><v>v<>^v^><<<v<<^>><>^><^^v<v><^<<v<><<>>>^>^^<^<<><><><><<<v<vv^vv>^<<vv<>v<v><>><>^v>^><^<v>v<<>^v<<<<><<^v^<>v^vv^^^>>vv><vvv<<^<<><<<<><v>^<^^^^<>>v^<><^vv^>^^><^^>v><^v^><^v<v><^v^<^><<vv^>v^v>><^v>v<v><vv^<>v^v^>^v<>><<>v><>><><<>^v>>^>>^>>v<<<>>>v<v<<v<><<<v^<<<>v<<v^v>v<<v^<>>^>^v^^^v^vv^v^<^><^^vv^v^<<<<^><>^^v^v<vv<><vv^><<^>v>^v<v><>><><^<v^vv>>>v>>><<<v<<v>^vvv<^^<v^>^v<v^^v>^^>^^v><v<<>^v<^v<^v<>^>vv<^v<v<v<<vv>^><v^^v>>^v<^vv>^>>>>^^v<<vv^^^v^<v^v^>>^^^^^vvvv^^><vv>>^^><><vv>^v>^>v><vv^vv<>^>vv^v<>^^^v\nvv>v^vvv><><>>vv>>>^^>>><<^vv^^^v^^><>^<v^^v>^>v<<v>><v><^v^^<v^v>>^>><v<^>><v>v>^v<>^v>^<>v<v>^>vv^<v<vvv>v>v<^vvv<>v<<vvv<^v><>>^v<><v>^<<>>v<>>^^><v<^^v^^><v<vv<^vv>^<><>v><<>><<v><v>><vvv<^>v>><v<<^<v^^<v><v<<><><>>vv>><<>^><>>^>>>v^<>vv>^<<>v>^>><<vv><^<v<v<vv^>vv^^vv><<>vv^vv><><^v<>>>>>v>^v<vvv^<vv<<v^<v<<^v<v^^>>>v^vv>^<v>>v^>v><^<^vv^v^<^v>v<>v>^vv^<^^<>v>^v^v^><<^^<^v^>vv^v^>v>>^><^><<<>>v^v>v<vv^v<^^v^^<v><>v^<^^v<<>^v>>^>^^<>v<>vv^^^<vv^<<^^>><>^v<<>>v>^>^<v<^vv^>>>v<v^^><<>vvv><>v<vv^^<^<^>^^^v>>^<>^v<<^<v>^^>^^>v<^v>v>^^v>^>^>>><<<^v<><>v><<<>vv><<<>^><>><^><v>>>><^<vvv^>vv><<>^<>^<^^v^^^>>^<>v>^<v<><^^^<vv^>vv<^>^^vv>^>^^vvv^>^v>v^<v^v>v<<<>>>>><vv<<<vv^^<<<<><v^^v^vvv>>v^v>v^>>^^>^^^^^<<>>>>v><<><<vv^<v>>v<v^v<><>^^>^v><>v>><<^>v^vvv<<vv<vvv>^^>vv>^<>v>v><^^>>>^^v>^^v>><<^>v<>><>v<<<<v<>^vv<v<v<>v<>^><>v<>^>>>>><^>^v^<v^v>^^><vvv>v<^^v>>^<>v^v>^>^<^><<>v><>v<<>^^<>v^^v>v>>><><<<>^v^>^>v^^>^^vvv>v^>^><<v>v>vv^<v<^<^>>^^><^>^<<>v^<v><v<>>^v<<v^>^^^>v>vv^^>v^>v^>v<<v>><>v^\n<^v<vv>><v><<<<><^>>>^<><v<v^vv<>vv^^vv<^<<v^^^^<^<^>^<>>v<<v<^v^^^>>><<v<v<v^v>>v<^^<<v><><^^<^^v<>^<^><<^^<>^^^v>>>v^^v^><^><>>>v>vv^^>>>^<vv^vv<^><^<^>^v>v><^v^v^<^<><>v^^^>>^><>>><>v>^<<^<>v>>^<^><>><vv>v>>v>v^<^v<^^<^><<>>>vv><v<v>^><v<<^^>>v<>>>v^^>^<v^>>vvv<vvv><^v>^v^<v<vv<<vv^vv>v^^^v^>v>v>^<v><v^>><<v^^><vvv^^vvv>^<^<>v>^<v>^<v>^^<vvvv>^<>v<v<>v>><v^>>vv>^v<^v<<^><v>>^<<^>vvvv<>^vvv^^v<<^>^^>v^>^>vv^^>>>^<<^v^v>v<^>v^^<>v<>v^><v>>^^^v>v<v>^v^v<<<<<<v<^^>>>>vv<^^v>^>^><^<>>v>><^^^^^v<<^v^v^>>^^<>^<v<vv>^v<<^>^>v<>^v<v<^^<v>^<>><^v>^v>v<<>^v<^>vvvv<<>vv>^<<vv><>^<<>^^<<<>><>^^^v^v^>vv>^><^^^><vvv^<v<^<v>v^v^v><v^v<<<<^vv^^v><v^<v<>>^>>>^>v<><^<^^>vvv^>^^>v<>^^^<<^v^<<vv^<v^<v<<^^^v><v>>^<v>>vv^<vv^^v<v^<^>^^^^^>><>^><^v><<^v<<>vv>>v^<<<^^<v>>^vv^>v>><v^<^>^^>^>v>v^^>v^><><<<^^><v<<vvv^<><><^>>^v^^>v><^><v<<^v>vv><><>><<><v<v<<v>^v<<^v><^v^><<v^^^v><v<<v<^<^>v>>^>>^v<v^^vv^>v<<v>v^v^v>^<^^^v^><>^>>^v^^v^<<^<><><>>><^v<vv<>^v>v<^^vv>vvv>vvv<^<^v><^<>^><^^<v^v>v<^^<^vv^>v<^v<^v^v<\n><<>^^>v<^^v>^v^v<><vv<<<<^vvvv^^<<<^>><<>v<<v><<vv>^v<^<<<^<>^^vv><vv^>v^<<v^>v<><v<^v<>v<<<^vv^<>v^v^><>>>v>>^>^^vv<vvv<v<^><^v><^<^>^^vv<<><v>^>^><>vv>v>vvv>>>><<<<v<>v^<^><>v><><v>^><vv^vvv>^<^<<<<v>vv><<v^<^>^<^<^<><<^v>^vv><^^>^^>vvv>>>^>v<^<v>^^<<v^>^><^<^^>^<v>>^<v>>v>^vvv^<v>><>^>^<<^>^>^v<<vv<^>>^^^^v<><^v<<vv^<v^<v<<<v^<v>><>vvvvvvv><<<v><>>v>>^>^>v><vvv<v<<^v^^v^^><v>vv^vvv<^v^<>^>^<^vvv^<^<><<v^v^^<<<^>><>^>v>v<><v^<<^^<vv<>>><>^^^^^>><v>v<>>^v>^^^^>^><<^^vv^^vv><v<>^^>^v<<^v<vv><v>vv>v^vv^v^<vv^v>><>v<>v^v><><>>vv<>v<>>>>^^<<<<><^^^^vv^v<v<v^>vv^<v<vv>>>^><>><<v<v<<<>^^><>^<<><^^<v^><<>v^>>^><^<><<><<v^>^^v<>>>^vv>vv>>^<><vv^<>^^<v^^vv^<^<<<v^<><>v^^<^^<<v^<^<^><<v<>^<^^v>vv><v^^>v<v^>^<<^v<^<^<v<^><<^^v<>>v<<>>v>^v^<^<<<><^^^^<>>v>>>>><>^<^<>v<<^^^v><v><vvvv>vv^^^^<<v><v><>^^>v^<<^v<><^>vv>v>v^><^<>v>^<v<<vv^v<^<v<^<<^v^>^>v><^^<<^>v<^<<^v<><^^><<<<>^>><^<v^<<^<<>>>^>^^^^<v<>^v<v<v^<<>^^vv^v<vv>>vv<^>v><<v>^v^^<^>^><<<<<><>>v<vvv<<^^^v<^^<>^^><v<>^^^vv^>v^v>>><^^vv>vv<^>\nv<vv<vv><><^>>>vvv^^<<><v^<>v>vv>^^><v^<>>^v<<>>>^^v^<^^vv<<<^v<^v^^>>^<^>><^>v<^<<vv<v>^^<^>>^<<^<v>>v>^^v><^<<<vvv^<<^^vv><^v><vv>><<^>>^v<v<<^><>v^v<<>>^v<><<v^v><v>vvv>v><>>vvv>><<^<>^<<v^><>>>^>v^^v<v^vvv^<>^^<>v<>^^<><v<>^v^><v^v^>v^^^v>>>v^v>>v^<^^^>^<v^v^>>^v^>^^>>^v>v>>><><>v^<<<vv>><>>v><^^vvvv<^<v<^v>>v>>v<<^^^<vv><>^^>^>><^^v>v^v^vv<<^v<<<^vv^<v<v^>><v>vv<v>v^<^<^>^<><^v<v^^<<<^>>>^>v^>v^><<<<^<v><<><>>^<<>v<>>>^^>v>>>vv>^v^>>v<vvv<>v^<<^>>^v^>><^^>v<^^^>^^>^>><>>><^>>v<><v<<v<v>^>vv^^^<^v^^^>v<>v^vv>><<^>>>vv>^v^v^v<v>^>vv>>v>^v<^^^^<<^><<v<^vvvv>v^^^>>>^<^v^^^v^v><<v^<^vv>^><<><<>>v>^>>v^v><^>><<v^v<vv>^v^>^^<>v^^^^>^^v<<<<<^>^<vv<>^vv<>^^vv^^^v>v^^^^^^<<v^<^><>^>>v<>^<v<^<v<^v^^>v^v>>vv^^^><><<>>^v^<^v>>^>><<^>>v^vv<v^>>>^>v^v>^v<<vvv><^^v<v<<v<^<>v>^>><vv^<>v>^v^>v^<v<>vvv^v<<<^>>vv^^>v>><>v^^<^^<^vvv><<v^>^>vv>><^^>^<v<^<<^>><>>>>>><^>^v>^^^<v^><<<>>vv>^>>^^<^>>^v^vv>>v<>>^><^<><v<<v^^^<v^>><>^^^v<v><v<v>^<^^>>^<>>>v^^^>vv>^^^vvvvv^^^v<<vv^<<^v<><v^>v^<v^^<^^<^<^vv<<^>\n<vv<vv^v^v>vvv<<<<<>^^^^>^><^^^v>^<<^^><v>>v>^^><>v><v><v^^>vv^^<<v<>vvvvv<>>^<><v<>>^<vv^^<>^>v>v<<>>v<v>>vvv<>^>v><>^><>vv>^<^>v><>v^v<><>>>v^v<^<^<<>^>^v><<><^<^>>^v<>v^v^vv>vv^vvv><^>v<>v^^<<<^><vv>>>^v^<<>>>vv<<vv<^vv>v<>v><<<v><>>v<<^><>^v^vv^v><><>^<<>>^v>^v^v^vv^<^<<v><<^^>v<^<>v<v<vv<v<^<vvv<><<v><><<>^vv^v^<v>>><>^>>^^<v>v<^>v>vv<v^^^^^<<v<><v>>^^<<vv^<v>v<v^<vv^^<^^>v<^<v<<^^v><^v^v>^v<>^<>><<^^v<<v^v>^vv><v>^^^^^v^v><^vv^v><vvv>><vv<vvv><v><v>v<<^^v^^<^v^<^^><>>>vv^<v>v>^v^>^<<>v<>>v<^^^><^<v^><^^v^<<vv<<>v^>^<v<<^>v<^>^>vv>>^^<v>^^>v><<<^v><<<v><<><v<<>^v<<^>>^>><>><v<^>vv<>^v><v^vvv<><^^^^^>v<^v>>v>v^vv>^^^<<><<^<^^v>vv<^v><<v^>><><>v^^<v>v^<v^<<vv^>>v>v>>^>^v^^^><^>vv><v>>v<>>v<<>v^^v<<<^><^<v>^>^<v<>><v^v><v>vvv><^v<><><<>v>^>><><>>>><<^^><<>^^v>v>^^v<v>^^^v<>vv^><^v^<<^<^<<^<^>>^>v<v^vv^^^v^<>vv>v>v>>>>v>^^^^>^^^<^>^^<<>vv^>><vv>v<<>v>>><><v^<^^^<<>>^^^<^<<v^^<>vvv>v^^v<>v<^<v^>>>^><<>^>v<<<>v<><^^<v<^v^^><v><><>^>^>^>^><>v<>>>>^<<^<<vv>>><>><<v<<^<>v^<>^v^^^^>^<^<v<^v\n^<>>^<vv<>^^v^<vv^v<<<>>^v>v^<v><<v<v^<^>vvv><><^v>>^<<^v<^vv>>^^v<^^><vv^vv^>v<vv<v<>vvvv<^><<<>>v><v>><<^<v>v^>vv<<^vv<v^v>^>>>>>^^<<<^^>v^<>^v>^><^vv<>^<<<<v<^v<>>vv<^v>^>v^<<^<^^<<<>^<<<<^^v^>v^<^v^vvvv<vv<^^<v>^^vv^<>>^^^^v^<><><><><^>^>>v><<v<>>><<^v>>v^v<<<>>^v<vv><<^^<>>v>^>><>vv^<^^<vv<vv>>^^<^<v<^>>^>>>><>v^^>>><vv^v><^^^^^v>v>>v^>><<^v^<^>>^v^<<>vv^^><v<v>^<v<>^<<>v^<>^v^<vv>^>^v<<^<^>><v^v^<v>vv>^^v<v><v>^^^>>v^><<<^v^v<<>v>^^v>^^vvv^>v^>^<<><>v><v^^v><><^>^vv<<<>^>v><vv<>v>v^><><v><v>><<>v>v>>v><<>>v^^<v>^>>v^>^v<<>^^^^^><^<^<^v>><>v><v>>^<>>v>v>vv>^>v><v<^>^<^<<<>^vvv^>^v^v^v<^^^^>^>v^^^<v><v^v^>^<<^^<><^>^<^vv>>v^^^>^^<^v^^^><<<><v^>^><^>^v<^><<><><^^<^<v^v>>>v>>^<<<>>^>v>^<<v<<^v>^<^><<><<^>^^<^<<vv>v><^>v^>vvv^<<^^^v<<^^<><v<<^v^<v<^^^^v^>v>^<v<v<<^v><<^^vv>vv^<v<^>><<>v>v><v>vv<<v>^^<^>vv>v^vv<<<>^v>^v>v><^v>^<v>^vv<>><vvv^v<v^><vv>^^vv<<>^^>v^^<<v^^^><><v^>>^v>vv^>^^v^^>^><^<<<v<<<<>>>>v^^v<^^v^>v<v><>><^>^^^v>v><<<v<<>>^v^><^<<<^<>^v<<>^^^^><<vv>v^<<><vv<>>>vv<vv^<>\nv^<v><<^^vvv<>^vv<<v<^^v<<>v<>v>><<v><^^>v<^>^v<<v>v>>^><>^^>v><<^v^^^^><<<^v<v<>^>^v<v^^<vv<^v><^<v^<v^>^<>vvv<>v<><vv<v><>^<>v>v><^^<^v^>>^v<<vvv^<>^>v^<v^v<>v>v^>>>^^vv^v<^><^>^<><^^>^^<^^<vv^>>>vvv<^<<>v>><<<>v^v<<<vvv><vv^vvv^^<<>>>>v<^^>^vv>^^<<<v^^v>v>><v<^>>v<^v>vv<>^<><^><^><^v^^v>v^^<>vv>^<><^<<^>>^>>^><^^^<<v^^<<<vvvvv><>^^^^^>>v<<<^vvv<v>vv^<^<<<vv><^^<<vvvv<^^v^<v<<<^<^<^>>><<>>^>v>vv>^^^v^v>^>>>v^<<<<><>v>^><<v><<><<>v><^>v^vv<v><<<v<^<^<<v>v<<v^>^^v>><<<vv^<v^><^<^>vv<<><<>v^>v^<^^<<><><>>><><><>>vv<<>v<><<v<><v<vv<vvv>^>><^^<^^<^v>^^<><v<>v^^^>>>>>^v>^^v<>^vv^v<><><<>v<<^<vv^^<<<<v<vv<^v>>><<<<<^^><<<^<v>v>>><vv<v><^<^^vv<<v>^^><v>^<>^v<vvv^^^<^<<>v^v><^^^^>v<^^<<>>v^v<>>^vv>^>^vv<><<>>v><>vv^>v>><^<^^<<<>v<<<v>>^<v>><^>v>^>>v^>><v<^<^><>^<v<>v^^<>><v>>>vvvv>vv^^vvv<><vv^vv^^>>><>v<^>^^v<v^>vvvv>v<<v<v<^^v>v<^^<<>>v^vv^>^><<v<><v^v<^v>^v^<>^<^><<<^^>v>v>^^^<<^>v<<vv><^>^^<>>>v^<<v>^v^<v>v<v>>>v^v<^<<^^^>^v<><v><>>v>vv<v>>^>vvv<>^^<^<^^^^^><><><v<>>>>^^vvv^^vv>^^<vvv<^^v\n^<<^>^>v><>>^^^<><v>^^><><<>><>^>^v<v^^^vv<v>^^>^^v^>v^^<><<>^>v^>v<<>vv^>^>>^>^><<v>>^^vv><^<^^v>>^<^^>vv>v>^v^^>^><>^^<^^^^>v<<^>>>^v<>vvv<<>^v>^v<v^^^>vv><v>>vv^^^v>v>^<><^^v<<>^<><vvv>vv<><v<<><<><<<>>^>><<>^<^v^v^vv^<<><^^^vv^<<>>^<^>^>^><v<<^<>^<^<^<>><>v>><vv<>^<^vv>^<^^^>>v>^^v^><^v^>v^<><<<v^>v^v<<v>v^<^<v^v>v>v^^v<><><<^>>v>v><<<<v>><v^v<v<><<^>>^>v^v^^^<<><^^<><<<v^^^>^^<v^^v^<>^^>>><>^><<^>^<<<><<^<>vv<vv^>v<<^^<v<<^^v^>v<><>v>v>>v^v^>^<v^>>^^<v^<<><>vv^^>^^<v^<>v<<^v<<^<<><v^>><v^>>vv<^<>^v<v^><v<>vv><<>>>v>^v<^v><^v><^>^^<<<^vv>>>^^vv>vv<>v<<^>><<^<^>><^><>>v<<>>^v^>>>><^v<>^vv^^^^>^^v<>>><>^<<v^vvvvv^v<^^v>>v^>^>v>>>v<><^v<v<>^<^>^v^<>^v><><>>>^^<<v^vv<v^>>>><>^v<>>v>>>>v><><<^^><v^^^<v>>v<^>v<>v<<>><v>>vv><<<<^>v><v^<<>><<^vvv^v><vv><<^<>>^v^>v^v><<><v^v^<v<^>vv>^<<^^^^vvv>^v><^v^v>v^^<><>^^^v>>v^v^v>v<v>><vvv<<^<^>>v^v^v^><v^^<<>^<^^^>><^>^^^><v<<<v^<>^^<>>>>^>v>v>v<>>><vv^v>>>v^>><<^^<<^><<^^>vv^>^<>^^>^<>^>v<<>vvv<v^>>><^<<^>^v>^>^<><<^v>v^<><>vv>>^^^vv<<^>>vvv<<<vvv\nvv<^>>v^vv<vvv>vv^>^^<^>>^><<^v>v<^v>^<v^><<^>^v^<^>vv<<>>^v^^^^><><^v^v^<v>^^<>^<<>v^>v^<v>vv^<v>^<^v>><<^v<<<<<>^<vv>v>><<v>^^>^vv<v<v<v<<v<<>>><^vv>>^^<^vv><>^>vvv<<v<vv^^<<>v^<>v<<><<>v<<^v^^<v^^><vv^<^>>^<^><<^^^^>v<^^>^>^^^<<^^v^^<vv>vv>v<^v<vv>^<>^<^><^^v><v^v^>^v^<^^vvv<<<<<v^>^v>^>><^<^^<vv^<>^><^^v><^><<><<^>^vvvv>^v>>v>v>><>vv^^<v<>^>^>v>>>>v><^>^<<v>v><>><>^v^^<^<^><<>>vv<^<^^>^<^^vv<^^^>^>^><>^>>v>>v<<^v^>>^>>>v^v<v^v>v<^>>v^v>v^>^v<^v^<<<^><>v>v^><^v<>vvv<^^<^<v>^><^<vv<<<<v^v<v^<>>v<v^<v<v^^><v^<v<><^>v^><<<<<^<>>>vv<<>^^>^v<<<<^><>^><<v<<><^^<>v<^<v<vv>>^v>>>^<v^>>>^>^<^>><>v>^<<vvv<<><>v><<>>^<>^^<v>v>^>>^v>v^>v<v<<vv^<>v^^v<><vv>>^^v>><^vv>v^v<<<^><v><v>>>^^>^<^<>vv<^<v>>^<^>><>^><<v>v^v>>^v^<^v><<<>>vv<><^v^v<v^>>>><<<v<^v^v<v>^^><^><v>^<>^v^^<^^>v>^<^<>vv^>vv>>>^>^v^^>^^>^v^vv^v^>vv^>^v^^<<v><v^v<vv>><<<<v^vvvv<v>^<<vv^><^v<>v><v<v><><^^^>^<><<v^>^><<vv<v><<vv^^<<^><^vv<>>v<^>>^<>>>v>^vv<^v^v<^vv^<>>>v><^>v^v<^v><^v>v^^>>>^^v^vv<^<><vv^v<^^<vvvv>v^^<v><<><^v<>><v<<<\n<^<>^>^>^<<^v>><^<<><v^<^^>>v^^^>>>><v><^^v^^v<^<<v<>><^><><^v<<>^vvvvvv^><vv^>><^vv^^v<><>>^v^^<<>^<vvvvv<<v^<vv>v^>v<<>>>^v<^v>^>^v<vv>v^^<v<><^>v><^v^v^>><>^<<^<v<><v^<vv^v<<^>v>^^>>vvv<>v>v>>v^^>v^v^^<^<<v^^>vvvv^>^v<<v^>^<<^>vvv^>vv^^^^<v<^>v>v><vvv<<>^>^>vv><<^^<>^<v<^vvvv<^vv>>vvv^v<<><<^<>^<vvv>><>>>><^^>>v>v<v><<>>vvv><<^<<><v^>v<<<^><>^<>v>v>^<>vv>v<v<v>>>^^^^^<v^<^^>><v>>vvv<<^v^<^^^^>vv^<><<<^^^<>>>^vv<><<^>v^v^^^><^<<v^v><<v<^^>^>>^<^^<>^>>^>v<<vv^>^><^<<>><vv><^v<<^>v<>vvv^^vv<><><<<v>^><v>v<^vv><v^vv<^<^<v><^v>><>>>>><>>><>v><<>vv^v^>v<v<<>^^>v<^>v<>v^<>><^v^>^v^vv^v><v<^>^><><<<^vv^<^<<v^<^><v^v^v^v<<>^^v>v^v>><>^v^v<^^<<vv>>>>vv>>^<vvv<^>^^^^v^^<<v<>v<>v^<v<>><^<>v^<>v^><v^^>v^v<<^><^>>v<<>^v^^^<v<<<^^<^>>^vv><v<<<^>><>>><<^><v><<>v>^^^^v<v>v^^>v^<<vv<>><v^^vv^^><^><^<v^><v>v^>>vv^^>^^vvv^^>>><v^^<^<>>>v<v<>>v^^<<>v>^<>vv<^v>v><^vv<><v>>^v<>^vv^>>v^vvv^vv^>^>^<^^^>^vv^>v^>^^v>^^v^^v>^^<>v<v<<>>vv>^^<<vv^^<<<<>^<>^<><>^^v<v<v<vv^vv>v^<><>>v>v^>^v>^vv<^^^><><>>>v>vv>><>v\n^v<<^vv<<v>>^^v^vv<v^vv^><<^vv>^v<^>^^<vv^<^vv^^v^^<^>>v^v<<<v^^^vv>>^vv><v<>^v<v>vvv><^^v<>vv>>v>v<><^<>>v><<^><^^v^>><>vvv^>^v<<>v><>^v>>^vv^vv>^<<^>^^^>><v>v<<v<v^>>v<>v>^v>^^^^>vv>>^^<<^<<<<>^><<><<>>>vv^<^vv>^><><<vvv^>^vv<<v<^^>^^v<>^<^^vv><<^<^^>^><<vv<^<<^vvv^^><v<v>v>>>><<<^<v>><<v^^v^<^v<><^^vv><v>^>>>^v><>><>vv<>^><^v<^<<v<<v<v<><^vv^v^v<>^>>v^^v^>v<>>v<^v^>v><v>><>^^>>><v^><v<<v<<^><>>vvv>v>><><<<^v><<v>vvv<^<^><><<v^vv<v<^<>v>>><><<^^^^>>^<>^>>v<v<^v>v^^vv^^^^<>><>>>v>^>vvvv>^<v><^><<<>^<^<^<>v><^v<>><>vv^>vvv^>>vv^>vv^<<v^v^>^^^<>>^><v>v<v><v<>v^<<^^>v>^<><v<vv<v^^v^^<><<<^<^>^>><>><>v^<^<^^vv<>^^<^<v<><v>v>^<>v<vv>v>vvv^<v><^v><><v<^v^>v<<^v<^v^>>^^>^><v>><<^><><^>^v^<>vv>^<<v<v>^^<v>><^<>^^<^^^^v^<<v^<><v^^<v<^^v>^^<>v<<>vv^<^v>>v^v^>>>v>^^>v^v>v<<>v^<<>^>vv<^vvv<><vv^<^>^^>>>^<v^vvv^^<^^v<<>v>>v^>>>^<><^>>^<<>^><>^v^^><vv><<>v^<v<<v^v<v>>>>v^>^><v><<vv^<v>^>>vv^^><>vv<v^<<<^^>^>^<>v<v<<<>><><^^><^v<><>v>><<^>>^><<>^>^<^^^^^vv>v^vv><<^<<><^>^>^v<^v^^<v^>^<<v^^<>^>>v>^^>\nv^v^<<>>vv<><<<v>^>>vv<><v<^v><>^^><<>>^>^<^v>><<^>>>v^><^>>v><v>vv<^<>^<v^>>v^>^<<<<>^^>v^^<<^<^<>><v<^^<v>><vvvv><v<^>^vv><><^^^>^^v>^<><>^<><^><>^>v<<^^v><><<v>v<><vv>>>>^<<<^v^>^>^v<<vv<vvv<><>>>^<>>^^<>^<vv>v^><vvv>^v<v^^<vv<><>>v^<^v^<v<v>^vv^<>^><><v<^^<^v^<><v^^><v<v<<>>>v>^^v^v^<>^>vv>^^<^^vv^><v><^>>v<<<v^<^^vv<^<^v>><<>>vv<>^^v<v>>vv<v^^><v<^v>^v>^>^>^<v>>>v>vv><>^^<><^^v<><<^>>^^<v^v^v<^<v><^v><>^>vvvv<>v<v^>vvv^^<<<<v><^v<vv^^<v>>>vvv<<>v^^><^<<>^v^<^<v^>>^v^v<<v>^^v>><<v^>v>>^<<^vv<>v^v<v<vv<>>>><>^v>v<>v<>^v^<>v><v>^^><>^^^<v>>^>vv<v>^>>>^^^^<vv<^v<><vv^vv<^>>^^^v>v^<>vv>v^><v^>>v^>vvv<^<>v^>>vv^<^<><^<>^v>v><vvv><v^^>><^^<<^<^^v<^^^<v<v>v<>>^><>^><<><v<^vv>><><><<^^^vv>>>v<^vv^<<<>^<><<^>vvvvv^^^<^<<^^>>^^<<^<^vvvv<>v^><^^vv>^<>><<>>>^>>^^v<<<vv>>v>^>v>><v<<v^^v>^<vvv<v>^>vv<vvv^<>vv>>v^^<^<>v<<v<<v<v><<>>^>>^^>>>><>>^^v>^>>v<^^>^<v^>^><^>^^^v>><<<<<vvv^>>^v<v>vv^<<<v><^><^v^^^<<<^>><^^v><>v^v<>>v^>v^<>^<^<^v^<v>^vv>>v><<v>><^<^<^vv<v<><<>v<><><^^><^^^v>v<v<>v^<>>^><^vv\n^<^^^>>>^<v<<<v<<^>^v<^^>^><v<^<^<>v<>^><^^><><>><>^^^^>^^>v>^<v>^vv<^><>vv<^<v><>^^<<^>^vv^vv><^v<^>vvv^^vv<>v<^<v^<v<<<^>^<>^^<>^vv^^v<<v>v><^v<>vv><^<><>v^<><<^>>v^<>>^<v<v>><^^>v><<>^>^v^>v<^v^>>^<><^v><v<<<><v^^^^^vv<vv<v^>>v<<v><<>^<<>v>^v><<v<<>^>>><<>^^>^v^v^^>vv<>^><v>><v<<<>vv^^v^v>^^vv^>v>v^^>v^<^vvv<><>^<^<<^^><>>v>v>v<<v>v^>>^^v^^<<<^>v>^v><vv<<<vv<<>>^v^><>^^>v<^<>^<v>><v>>>v<<<^>>^vv^^<<<^<<>v^>^>^<^^^>^vv<><^>v^v<>>v>^<^vvvv^v>>v^<>^<v<>><>v>^v<<^vv>vv^v<><v><^^>><>>><<><^^<vv>v^>v>v^^v>^<v>v^<<vv>>^<<v<v>^^^<>^>>vv><>><<<vvvv<<^<^^>^<^vv>^^><^v<^>v<v<>^v^^v^<^<<>>v^>vvv<v^<><vv<v>v>>^>>vv<v><<^>>^<>^vv^<vv^<>>><<^^v^^<^^vv^>^<v<<>^<>^v>v<><v<v>v><>vv^<v>>>^>^<><^^v^vvvv^>^>v^v<vv<<>>v>>v^vv^><>v><<>>v<<v^^^<vv^^v>>v^>v^<<v^^v>>>v>v<<vvv^>v<^^v^>v<<^vv<<v^>><^>^v>^vv>^^<v<vv<>^><^^<>><v>vv<vv^>vvvv>vv<v<<v<<>v<^^>^<><>vv>>^v>v^<<<<^>>v<v<v<vv>>>><><v>>^^^v<<v<v^<<^^<>^v^>v<>^^v<v<vvvvv^vv><vv^v>v<^^>v<<<<>v^><<>^v>^<v>^^^^<v>>^>^v><>vv><v<^<^<<<^>v<^<^^><<^v^<<>><^<>^>v\nv><v>^<v^<^^>v>^^v>vv<>>^v<>^v>^>v>>^^^^v>^vv>vv<<<<^>><v><>>vv^<>^><v><v>>>^>>><vv<^^v<>><<vv^<^>>vv^<<><v>v<v>vvv^^^><v<<^v>>^<<v<^<<><><vv^><>^^<v^>^^<<v<><<^<>><<<^^>v><>><>>v><v<vvvvvv^>vv^<<^<^vv<>>v^v><^v>^<>^^v>^v<^^v>>>^vvvvv<<<>v^<><><<^<>>vv>>v<<><v>>v^^^><<>>^<>^>^<^vv^>^>^^>>v^v^>^<v>v><v<<v>v>v<>>^v>^<<v^vv^v<><v<<^>>v><>^<v>^^v<vv^<<v^<<>^<^v<^vvv>^vv^<v>^^v>v<>v^>v<^<>>><>><<v>vv^^>><v<^v>>v<<>>>>vv<v>><^^^v>vv^<>>^^<<v>^v<>>v<^^>>^<>v^^><><^^>^^>^v><^^^^v^vv>^<>^<^^<^>^>>>>>>v^<<^v<<>>v^<v^>^><vvv<>>>^^<v<>>>v^^><<vvv><<^>v>v<^><^^>v<>><<v<^vv<<<<v>>v>v<<v^<<>v>>><<^<vv^>><<>^>vv<<<^v>><<v>><^><v<<^<^vv^><<v><<<^v^vv<>v^^v^<^^>vv<<vv^>^v<vv><<v>v^v^v^^^<^v>><^^^<>^^^<v<>vv><v<vv<v<v^vv><v>^^^><v^v>>><><>>><>>v^<>v>><>><^v<><><<>^<><vvv^<v<vv>v>><v>^<>^^^<vvv^>>>v<>>v^>>>>>v^^<<^^<^<<^^<vv>vvvv<>v<^v<v>>^v^^^^^<>^v^<v<^><v<v<^><v^^^>>^vv^>>^>v<^<<^>^>>^><vv><<v<^v>>>v><v^>>vv>>v^v^^<^^>>>^<^v>>v^vv<^<^v<<>v>^><>>^vv<>v<>^<>^^vv>^<>vvv^^^><^^<>^v^>v>>vv><<<^<>v>>v^<^^<^>\n><v<v^>vv^<>vvv<<v><<>vv<<^><^<<^>^<^v>><<<<>v>><>^^v<^><^>>vvv^<v<<<vvvvv<v<v<vv^v<>vv>>>>v<^><>^><><vvv>>vv>^>><><v^^<<v<<v<vv>v^v<<vvvvv>><>>^>v><<^^><<^^>v<<vv<>vvv^^vv<vvv<^<>v>><^<^v^<<v^><><v<<^v>^vv<^^^v^v^>v^v>v><<v^v<<v^^<v>>^<^^>^><^>^<^>^^>v>>v^>^>>>^v^<<>^v<v<^^>^v>>v><^^><v^<<<<v<><><^>>v><<vvvv^vvv>^<^v^v^^>^>^v^<<<v<>^>>>v^>><^v<<>><>>^vv<<^^<>>v^<<><<<>vvvv<^^><v^<<vvv<>><v^>^>v>^<^vvv^><<>v>v>v^^^v>><>><^<v^<>vv^>v^^>^>^<^vv>>v>^<^>v<<><vvv^<<v>>^<><<^v<>><v<^^^v^^<vvv<<>>v^^<vv<<><^>^^>>^vvv>vvv>vv^<><<^>^><>v>v<<>^<><^^><>vv^><><^<^v^><<><>^vv>>>^v>>vv^vv<>^^^v<^^<vv>>>^>^><^<v>>><>>vv>>v^^^<v><v><vv^vv^v<^v^^^<><>>^>^v><^<>>>><v^>vvv<<vv<<vvvv^<<^v>vv<<^^><<^v<^<>><^v<v^^^>v^>>^<^<<<vvvv<^>>>^vv>^^v^><^><<<><>>vvv<^^<>vv<<^<<v^^^^^<^>><><<vv><v<v>v^^vv>^^vv>v<<<>v<<<vv<<vvv>v><><<>^v<>>^>v^<><^><^^>v^<<><<>^>v^<>v<<<>^<^v<vv<v^v^^vv>v<^>>v><^>><>>v<<<^vv<<>^v>><v<<<v^><v>v>v^<v<<<<<>><>v<v^>^vv^<>>^v>^^>>vv>>>^v>>><<<v><^>v<v>^<>^vv<^v<<^v^<><vv>>>>v<^v>^<v^v^^>vvv\n><v<<<^>^<<v><^<<<<<v><v<^v^>v<<>>^<>vv<<><^<v^^<><<v>vv<>>^v^<>vvv^<v^^<<v>v^^^^>><<><v>^<^<<v><v<v<<v>v>^vvv^^<vv^^v><>^^vv<v^>v^<^><<<>>vv<vv^<>v^><^>>^>^<><<>^>v<^v^vv>>^><<>vv>^>v>vv^<>vv>v^<>>vv<>>v>^>>vv^<<<vv^>v^vv^>>v<^^<<^>^^<^v<<<v>^>^^v<<<<<><<^>>v>v^^<v>>^>^<><<<<vv<^^<v<>v^^<<^vvv<^^<v^^v>^<>^><^<^>>v^^>>>v>^<<<<^^>^v>>>^v^><^<<<>><^><<><v<^<<^<<><>><>>^^^>v^>>>^>^<v^v>>v<v<v^><<v>v<>^><^>^v<>^><<v>>v><vv^vv><<v^vv>>^^vv^<^<<^v^^<<<<v>>>><>><><><vv>^v<><v<><<<v<v<>v^<<<^^>^^<>^v^v^<v>^<<<v^<^^v>v^><v^<v^vvv>>^>v><>><>v><>><v^<<v>^vv^v^>>^vv>>^<^^><<>v^<^<vv>>>><><>^^>^^v<<<v><>><<<<><>^<^v>^<<>>>v><^<v^vv^^^<<<>>^<>vv<<v^<v<>>>v>^<<>>v><^<<^<^><v^>vv^v>>^v^v>^><^v^vvv^>>>><<>><<^^^<^^<<<v>v^vv>v^^v<vv><v^<<<^<^<>^<><v^^<<^^>><<<^v<v<>><><v^v>>>vv^>v>^^>vv>^><<vvv<>vv^^>^<><^>^<>><<><><><v^>^^<^<>>^^<<v><>>>^><><^<><>^>^v^<>vv^^>v^<^<>^v<>v>^v^^v<<^^v^>><<>>v^^<<<^v><^^<<^<>vv<>^><>><><^>v<<>v<^<v^>^>v^>^v<><<<^<v><<>v<vv>^<<^<<^^>>><<>^<vvvvv^>^^v<^<<<v^vv^<v<^v^<>v<v^^><'

In [4]:
test_input = """##########
#..O..O.O#
#......O.#
#.OO..O.O#
#..O@..O.#
#O#..O...#
#O..O..O.#
#.OO.O.OO#
#....O...#
##########

<vv>^<v^>v>^vv^v>v<>v^v<v<^vv<<<^><<><>>v<vvv<>^v^>^<<<><<v<<<v^vv^v>^
vvv<<^>^v^^><<>>><>^<<><^vv^^<>vvv<>><^^v>^>vv<>v<<<<v<^v>^<^^>>>^<v<v
><>vv>v^v^<>><>>>><^^>vv>v<^^^>>v^v^<^^>v^^>v^<^v>v<>>v^v^<v>v^^<^^vv<
<<v<^>>^^^^>>>v^<>vvv^><v<<<>^^^vv^<vvv>^>v<^^^^v<>^>vvvv><>>v^<<^^^^^
^><^><>>><>^^<<^^v>>><^<v>^<vv>>v>>>^v><>^v><<<<v>>v<v<v>vvv>^<><<>^><
^>><>^v<><^vvv<^^<><v<<<<<><^v<<<><<<^^<v<^^^><^>>^<v^><<<^>>^v<v^v<v^
>^>>^v>vv>^<<^v<>><<><<v<<v><>v<^vv<<<>^^v^>^^>>><<^v>>v^v><^^>>^<>vv^
<><^^>^^^<><vvvvv^v<v<<>^v<v>v<<^><<><<><<<^^<<<^<<>><<><^^^>^^<>^>v<>
^^>vv<^v^v<vv>^<><v<^v>^^^>>>^^vvv^>vvv<>>>^<^>>>>>^<<^v>^vvv<>^<><<v>
v^^>>><<^^<>>^v^<v^vv<>v^<<>^<^v^v><^<<<><<^<v><v<>vv>>v><v^<vv<>v^<<^"""

In [5]:
# b_in, moves = test_input.split("\n\n")
b_in, moves = input.split("\n\n")
in_board = np.array([list(line) for line in b_in.splitlines()])
moves = moves.replace("\n", "")

In [6]:
EMPTY, ROBOT, WALL, BLOCK  = 0, 1, 2, 3

In [7]:
in_board[in_board=="."] = EMPTY
in_board[in_board=="@"] = ROBOT
in_board[in_board=="O"] = BLOCK
in_board[in_board=="#"] = WALL
in_board = in_board.astype(int)
print(in_board)

[[2 2 2 ... 2 2 2]
 [2 3 0 ... 0 2 2]
 [2 3 0 ... 0 3 2]
 ...
 [2 0 3 ... 0 0 2]
 [2 0 0 ... 0 0 2]
 [2 2 2 ... 2 2 2]]


### part 1

In [8]:
dirs = {
    "<": np.array((0,-1)),
    ">": np.array((0,1)),
    "^": np.array((-1, 0)),
    "v": np.array((1,0)),
    }

In [9]:
def try_move(yx, dir):
    tup_yx = tuple(yx)
    if board[tup_yx] == WALL:
        return False
    if board[tup_yx] == EMPTY:
        return True

    goal = yx + dir
    tup_goal = tuple(goal)
    if try_move(goal, dir):
        board[tup_yx], board[tup_goal] = board[tup_goal], board[tup_yx]
        return True

    return False

In [10]:
board = in_board.copy()
r_pos = np.argwhere(in_board==ROBOT)[0]

for move in moves:
    dir = dirs[move]
    if try_move(r_pos, dir):
        r_pos += dir

In [11]:
board

array([[2, 2, 2, ..., 2, 2, 2],
       [2, 3, 0, ..., 0, 2, 2],
       [2, 3, 0, ..., 0, 3, 2],
       ...,
       [2, 0, 3, ..., 3, 3, 2],
       [2, 0, 0, ..., 3, 3, 2],
       [2, 2, 2, ..., 2, 2, 2]], shape=(50, 50))

In [12]:
int((np.argwhere(board==BLOCK) @ [100,1]).sum())

1475249

### part 2

In [13]:
BLOCKL, BLOCKR = 4, 5

In [14]:
in_board_wide_l = in_board.copy()
in_board_wide_r = in_board.copy()

in_board_wide_l[in_board_wide_l == BLOCK] = BLOCKL
in_board_wide_r[in_board_wide_r == BLOCK] = BLOCKR

in_board_wide_r[in_board_wide_r == ROBOT] = EMPTY

shape = in_board_wide_r.shape
in_board_wide = np.empty((shape[0], 2 * shape[1]), dtype=int)

in_board_wide[:, 0::2] = in_board_wide_l
in_board_wide[:, 1::2] = in_board_wide_r
print(in_board_wide)

[[2 2 2 ... 2 2 2]
 [2 2 4 ... 2 2 2]
 [2 2 4 ... 5 2 2]
 ...
 [2 2 0 ... 0 2 2]
 [2 2 0 ... 0 2 2]
 [2 2 2 ... 2 2 2]]


In [15]:
def try_move(yx, dir):
    test_move.tested = set()
    do_move.moved = set()

    test = test_move(yx, dir)
    
    if test:
        do_move(yx, dir)

    return test

def test_move(yx, dir):
    tup_yx = tuple(yx)
    
    if tup_yx in test_move.tested:
        return True
    test_move.tested.add(tup_yx)
    
    if board[tup_yx] == WALL:
        return False
    if board[tup_yx] == EMPTY:
        return True

    goal = yx + dir
    # tup_goal = tuple(goal)
    
    if board[tup_yx] == BLOCKL:
        return  test_move(goal, dir) and test_move(yx + dirs[">"], dir)
        
    if board[tup_yx] == BLOCKR:
        return test_move(goal, dir) and test_move(yx + dirs["<"], dir)
    
    return test_move(goal, dir) # for robot and left right moving block
        


def do_move(yx, dir):
    tup_yx = tuple(yx)

    if tup_yx in do_move.moved:
        return
    do_move.moved.add(tup_yx)

    if board[tup_yx] == WALL:
        return
    if board[tup_yx] == EMPTY:
        return

    goal = yx + dir
    tup_goal = tuple(goal)
    if board[tup_yx] == BLOCKL:
        do_move(yx + dirs[">"], dir)
        
    if board[tup_yx] == BLOCKR:
        do_move(yx + dirs["<"], dir)
    
    do_move(tup_goal, dir)
    board[tup_yx], board[tup_goal] = board[tup_goal], board[tup_yx]
 

In [16]:
board = in_board_wide.copy()
r_pos = np.argwhere(board==ROBOT)[0]
for move in moves:
    dir = dirs[move]
    if try_move(r_pos, dir):
        r_pos += dir

In [17]:
int((np.argwhere(board==BLOCKL) @ [100,1]).sum())

1509724

In [32]:
from matplotlib import pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter
from matplotlib.colors import ListedColormap
def update(ax):
    global r_pos, board
    colors = [(1, 1, 1), (1, 0, 0), (0, 0, 0), (0, 1, 0), (0, 1, 0), (0, .8, .1)]
    cmap = ListedColormap(colors)
    im = ax.imshow(board, cmap=cmap)
    yield im
    for move in moves:
        dir = dirs[move]
        if try_move(r_pos, dir):
            r_pos += dir
        im.set_data(board)
        yield im

In [36]:
fig, ax = plt.subplots(figsize=(7, 3.5))
plt.axis("off")

update_iter = update(ax)

board = in_board_wide.copy()
r_pos = np.argwhere(board == ROBOT)[0]
ani = FuncAnimation(fig, func=lambda _: next(update_iter), frames=2000, interval=1, repeat=False);

writer = PillowWriter(fps=30)
ani.save("assets/day15/aoc15Part2.gif", writer=writer, dpi=80)
plt.close()

![part2 gif](assets/day15/aoc15Part2.gif)